### ISSUE TITLE
Error after merge / sort / repack

### ISSUE THREAD

**Issue by jayhesselberth** [PacificBiosciences/pbh5tools#13]
Using the workflow outlined in:

https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign

I was able to merge 8 separate cmp.h5 files, sort them and repack them.

I tried to feed this combined cmp.h5 file into `kineticsTools`, but get this error:

```python
Traceback (most recent call last):
  File "/vol1/software/modules-python/python/2.7.8/bin/ipdSummary.py", line 4, in <module>
    __import__('pkg_resources').run_script('kineticsTools==0.5.1', 'ipdSummary.py')
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 687, in <module>
    sys.exit(main())
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 664, in main
    rcode = kt.start()
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 353, in start
    return self.run()
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 416, in run
    ret = self._mainLoop()
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 571, in _mainLoop
    self.loadReferenceAndModel(self.args.reference, self.args.infile)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ipdSummary.py", line 502, in loadReferenceAndModel
    contigs = ReferenceUtils.loadReferenceContigs(referencePath, cmpH5Path)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 51, in loadReferenceContigs
    (refInfoTable, movieInfoTable) = ReferenceUtils.loadCmpH5Tables(cmpH5Path)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 123, in loadCmpH5Tables
    cmph5 = CmpH5Reader(cmpH5File)
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/align/CmpH5IO.py", line 726, in __init__
    self._loadReferenceInfo()
  File "/vol1/software/modules-python/python/2.7.8/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/align/CmpH5IO.py", line 845, in _loadReferenceInfo
    raise ValueError, "Duplicate reference contig sequence or identifier"
ValueError: Duplicate reference contig sequence or identifier
```

- What is the best way to figure out which identifiers are the offending duplicates? I tried to load the file with `pbcore.io.align.CmpH5Reader` but it fails with the same error. 

- And if I am able to identify the duplicates, can I simply remove them (perhaps with another h5 tool)?

**Comment by jayhesselberth** [comment]
This was caused by duplicate sequences in the incoming fasta file. Identified using the `--debug` flag and identifying collisions in MD5 strings.
