### ISSUE TITLE
cmph5tools exits

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/pbh5tools#14]
Hello
I assembled a genome and wanted to polish now with Quiver the assembly.
For this purpose I downloaded smrtanalysis-2.3.0.

    pbalign --nproc 16 --forQuiver raw_input.fofn FalconAss_Clean1.fasta FalconAss_Clean1.cmp.h5 --tmpDir /scratch/local/eschmid/tmp/ &

After a while it crashes with the following errors:

 >2015-09-16 20:21:13,822 [ERROR] SortService returned a non-zero exit status. Traceback (most recent call last):
  File "/scratch/local/eschmid/smrtanalysis/current/analysis/bin/cmph5tools.py", line 240, in <module>
    sys.exit(CmpH5ToolsRunner().start())
  File "/home/eschmid/.local/lib/python2.7/site-packages/pbcore-0.8.5-py2.7.egg/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/scratch/local/eschmid/smrtanalysis/current/analysis/bin/cmph5tools.py", line 188, in run
    inPlace = self.args.inPlace)
  File "/home/eschmid/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/pbh5tools/CmpH5Sort.py", line 368, in cmpH5Sort
    myIndexer = Indexer.Indexer().compute
  File "/home/eschmid/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/pbh5tools/Indexer.py", line 39, in __init__
    self._dll        = ctypes.CDLL(self.SW_DLL_PATH)
  File "/scratch/local/eschmid/smrtanalysis/current/redist/python2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

The mapping worked fine and it generated a valid cmp.h5 file it seems that the sorting step crashes then due to cmph5tools.py . Indeed the error is reproducible if I execute just

    /cmph5tools.py sort FalconAss_Clean1.cmp.h5

To activate the smrtanalysis environment I sourced the /current/etc/setup.sh as normal.
Any idea how I can easily fix that ?
Thanks

**Comment by dalexander** [comment]
Best ask tech support here

@PacificBiosciences/techsupport , can you help here?
