### ISSUE TITLE
select and sort lead to malformmatted data?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/pbh5tools#20]
Hi there,

I tried to select reads by `cmph5tools.py`, but got an error for `stats` after sorting the selected reads. Here are the commands and error message. Could anyone help? Thanks!
```
cmph5tools.py select --outFile selected000000F_left.cmp.h5 --where "Reference == '000000F:1-190000'" --outDir . 000000F_combo.sorted.cmp.h5
cmph5tools.py sort --tmpDir /tmp --outFile selected000000F_left.sorted.cmp.h5 selected000000F_left.cmp.h5
cmph5tools.py stats --what "Reference" selected000000F_left.sorted.cmp.h5
```

error
```
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 240, in <module>
    sys.exit(CmpH5ToolsRunner().start())
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/cmph5tools.py", line 204, in run
    outFile =  self.args.outCsv)
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbh5tools/CmpH5Stats.py", line 65, in cmpH5Stats
    reader     = CmpH5Reader(cmpH5Filename)
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py", line 859, in __init__
    self._readLocatorById[refId] = makeReadLocator(self, refId)
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/rangeQueries.py", line 132, in makeReadLocator
    offStart, offEnd = offsets[offsets[:,0] == refSeq, 1:3].ravel()
ValueError: need more than 0 values to unpack
```

**Comment by yunfeiguo** [comment]
I checked the file after selection step. It seems RefGroup is not changed after selection, i.e. there were two ref IDs even if I explicitly selected reads aligned to first one.
