### ISSUE TITLE
AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'

### ISSUE THREAD

**Issue by aechchiki** [PacificBiosciences/pbh5tools#35]
Hi, I was re-testing an extraction to fasta using latest clone of pbh5tools - and I get an error I never encountered before:

`AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'`

Here is the detailed command-line that I run: 

```
/home/aechchik/pbh5tools/bin/bash5tools.py ZAsfUfaG_m150315_071532_42182_c100790302550000001823178109091543_s1_p0.bas.h5 --outFilePrefix test --readType subreads --outType fasta
```

And here is the full log:

```
/software/lib64/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/aechchik/pbh5tools/bin/bash5tools.py", line 166, in <module>
    sys.exit(BasH5ToolsRunner().start())
  File "/home/aechchik/.local/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/util/ToolRunner.py", line 112, in start
    return self.run()
  File "/home/aechchik/pbh5tools/bin/bash5tools.py", line 121, in run
    inBasH5 = BasH5Reader(self.args.inFile)
  File "/home/aechchik/.local/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/BasH5IO.py", line 677, in __init__
    for fn in self.file["/MultiPart/Parts"] ]
  File "/home/aechchik/.local/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/BasH5IO.py", line 345, in __init__
    else self._ccsBasecallsGroup
AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'
```

Any input on what might be happening here?

Thanks 
Amina 

----

PS: 

Here are my install steps: 

```
git clone https://github.com/PacificBiosciences/pbh5tools.git
cd pbh5tools
python setup.py install --prefix=/home/aechchik/
```

Here are the OS details: 

```
$uname -a
Linux dee-serv07.vital-it.ch 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/*-release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)

```
Log of the install:

```
running install
running bdist_egg
running egg_info
creating pbh5tools.egg-info
writing requirements to pbh5tools.egg-info/requires.txt
writing pbh5tools.egg-info/PKG-INFO
writing top-level names to pbh5tools.egg-info/top_level.txt
writing dependency_links to pbh5tools.egg-info/dependency_links.txt
writing manifest file 'pbh5tools.egg-info/SOURCES.txt'
reading manifest file 'pbh5tools.egg-info/SOURCES.txt'
writing manifest file 'pbh5tools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Compare.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Format.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Merge.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Select.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Sort.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Stats.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Utils.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/Indexer.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/Metrics.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/PBH5ToolsException.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/__init__.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/_version.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/cbook.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/mlab.py -> build/lib.linux-x86_64-2.7/pbh5tools
running build_ext
building 'pbh5tools/ci' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pbh5tools
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -I/software/include -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -I/software/include -fPIC -I/software/include/python2.7 -c pbh5tools/ci.c -o build/temp.linux-x86_64-2.7/pbh5tools/ci.o -O3 -shared
gcc -pthread -shared -Wl,-z,relro -L/software/lib64 build/temp.linux-x86_64-2.7/pbh5tools/ci.o -L/software/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/pbh5tools/ci.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Compare.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Format.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Merge.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Select.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Sort.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Stats.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Utils.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/Indexer.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/Metrics.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/PBH5ToolsException.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/__init__.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/_version.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/cbook.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/mlab.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/ci.so -> build/bdist.linux-x86_64/egg/pbh5tools
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Compare.py to CmpH5Compare.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Format.py to CmpH5Format.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Merge.py to CmpH5Merge.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Select.py to CmpH5Select.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Sort.py to CmpH5Sort.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Stats.py to CmpH5Stats.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Utils.py to CmpH5Utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/Indexer.py to Indexer.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/Metrics.py to Metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/PBH5ToolsException.py to PBH5ToolsException.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/_version.py to _version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/cbook.py to cbook.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/mlab.py to mlab.pyc
creating stub loader for pbh5tools/ci.so
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/ci.py to ci.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/bash5tools.py -> build/scripts-2.7
copying and adjusting bin/cmph5tools.py -> build/scripts-2.7
changing mode of build/scripts-2.7/bash5tools.py from 644 to 755
changing mode of build/scripts-2.7/cmph5tools.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/bash5tools.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/cmph5tools.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/bash5tools.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/cmph5tools.py to 755
copying pbh5tools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/pbh5tools-0.8.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pbh5tools-0.8.0-py2.7-linux-x86_64.egg
removing '/Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg' (and everything under it)
creating /Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg
Extracting pbh5tools-0.8.0-py2.7-linux-x86_64.egg to /Home/aechchik/.local/lib/python2.7/site-packages
pbh5tools 0.8.0 is already the active version in easy-install.pth
Installing bash5tools.py script to /home/aechchik/.local/bin
Installing cmph5tools.py script to /home/aechchik/.local/bin

Installed /Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg
Processing dependencies for pbh5tools==0.8.0
Searching for h5py==2.7.0
Best match: h5py 2.7.0
Adding h5py 2.7.0 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for numpy==1.14.5
Best match: numpy 1.14.5
Adding numpy 1.14.5 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for pbcore==1.2.10
Best match: pbcore 1.2.10
Processing pbcore-1.2.10-py2.7.egg
pbcore 1.2.10 is already the active version in easy-install.pth
Installing dataset.py script to /home/aechchik/.local/bin
Installing .open script to /home/aechchik/.local/bin

Using /Home/aechchik/.local/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /software/lib/python2.7/site-packages
Searching for pysam==0.14
Best match: pysam 0.14
Adding pysam 0.14 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for Cython==0.27.3
Best match: Cython 0.27.3
Adding Cython 0.27.3 to easy-install.pth file
Installing cython script to /home/aechchik/.local/bin
Installing cygdb script to /home/aechchik/.local/bin
Installing cythonize script to /home/aechchik/.local/bin

Using /software/lib64/python2.7/site-packages
Finished processing dependencies for pbh5tools==0.8.0
aechchik@dee-serv07:~/pbh5tools$ pwd
/home/aechchik/pbh5tools
aechchik@dee-serv07:~/pbh5tools$ ls
bin  build  dist  doc  etc  LICENSES.txt  Makefile  pbh5tools  pbh5tools.egg-info  README.md  setup.py  tests
aechchik@dee-serv07:~/pbh5tools$ cd bin/
aechchik@dee-serv07:~/pbh5tools/bin$ ls
bash5tools.py  cmph5tools.py
aechchik@dee-serv07:~/pbh5tools/bin$ pwd
/home/aechchik/pbh5tools/bin
aechchik@dee-serv07:~/pbh5tools/bin$ ls
bash5tools.py  cmph5tools.py
aechchik@dee-serv07:~/pbh5tools/bin$ chmod +x *
aechchik@dee-serv07:~/pbh5tools/bin$ cd ..
aechchik@dee-serv07:~/pbh5tools$ ls
bin  build  dist  doc  etc  LICENSES.txt  Makefile  pbh5tools  pbh5tools.egg-info  README.md  setup.py  tests
aechchik@dee-serv07:~/pbh5tools$ cd ..
aechchik@dee-serv07:~$ git clone https://github.com/PacificBiosciences/pbh5tools.git^C
aechchik@dee-serv07:~$ rm -r pbh5tools/
rm: remove write-protected regular file 'pbh5tools/.git/objects/58/d54ff3574617e047649730c31603a9052bc42f'? ^C
aechchik@dee-serv07:~$ rm -rf pbh5tools/
aechchik@dee-serv07:~$ git clone https://github.com/PacificBiosciences/pbh5tools.git
Cloning into 'pbh5tools'...
remote: Counting objects: 74, done.
remote: Total 74 (delta 0), reused 0 (delta 0), pack-reused 74
Unpacking objects: 100% (74/74), done.
Checking connectivity... done.
aechchik@dee-serv07:~$ cd pbh5tools/
aechchik@dee-serv07:~/pbh5tools$ ls
bin  doc  etc  LICENSES.txt  Makefile  pbh5tools  README.md  setup.py  tests
aechchik@dee-serv07:~/pbh5tools$ python setup.py install --user
running install
running bdist_egg
running egg_info
creating pbh5tools.egg-info
writing requirements to pbh5tools.egg-info/requires.txt
writing pbh5tools.egg-info/PKG-INFO
writing top-level names to pbh5tools.egg-info/top_level.txt
writing dependency_links to pbh5tools.egg-info/dependency_links.txt
writing manifest file 'pbh5tools.egg-info/SOURCES.txt'
reading manifest file 'pbh5tools.egg-info/SOURCES.txt'
writing manifest file 'pbh5tools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Compare.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Format.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Merge.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Select.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Sort.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Stats.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/CmpH5Utils.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/Indexer.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/Metrics.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/PBH5ToolsException.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/__init__.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/_version.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/cbook.py -> build/lib.linux-x86_64-2.7/pbh5tools
copying ./pbh5tools/mlab.py -> build/lib.linux-x86_64-2.7/pbh5tools
running build_ext
building 'pbh5tools/ci' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pbh5tools
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -I/software/include -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -march=nocona -mtune=core2 -D_GNU_SOURCE -fPIC -fwrapv -I/software/include -fPIC -I/software/include/python2.7 -c pbh5tools/ci.c -o build/temp.linux-x86_64-2.7/pbh5tools/ci.o -O3 -shared
gcc -pthread -shared -Wl,-z,relro -L/software/lib64 build/temp.linux-x86_64-2.7/pbh5tools/ci.o -L/software/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/pbh5tools/ci.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Compare.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Format.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Merge.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Select.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Sort.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Stats.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/CmpH5Utils.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/Indexer.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/Metrics.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/PBH5ToolsException.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/__init__.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/_version.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/cbook.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/mlab.py -> build/bdist.linux-x86_64/egg/pbh5tools
copying build/lib.linux-x86_64-2.7/pbh5tools/ci.so -> build/bdist.linux-x86_64/egg/pbh5tools
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Compare.py to CmpH5Compare.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Format.py to CmpH5Format.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Merge.py to CmpH5Merge.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Select.py to CmpH5Select.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Sort.py to CmpH5Sort.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Stats.py to CmpH5Stats.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/CmpH5Utils.py to CmpH5Utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/Indexer.py to Indexer.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/Metrics.py to Metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/PBH5ToolsException.py to PBH5ToolsException.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/_version.py to _version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/cbook.py to cbook.pyc
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/mlab.py to mlab.pyc
creating stub loader for pbh5tools/ci.so
byte-compiling build/bdist.linux-x86_64/egg/pbh5tools/ci.py to ci.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/bash5tools.py -> build/scripts-2.7
copying and adjusting bin/cmph5tools.py -> build/scripts-2.7
changing mode of build/scripts-2.7/bash5tools.py from 644 to 755
changing mode of build/scripts-2.7/cmph5tools.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/bash5tools.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/cmph5tools.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/bash5tools.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/cmph5tools.py to 755
copying pbh5tools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pbh5tools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/pbh5tools-0.8.0-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pbh5tools-0.8.0-py2.7-linux-x86_64.egg
removing '/Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg' (and everything under it)
creating /Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg
Extracting pbh5tools-0.8.0-py2.7-linux-x86_64.egg to /Home/aechchik/.local/lib/python2.7/site-packages
pbh5tools 0.8.0 is already the active version in easy-install.pth
Installing bash5tools.py script to /home/aechchik/.local/bin
Installing cmph5tools.py script to /home/aechchik/.local/bin

Installed /Home/aechchik/.local/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg
Processing dependencies for pbh5tools==0.8.0
Searching for h5py==2.7.0
Best match: h5py 2.7.0
Adding h5py 2.7.0 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for numpy==1.14.5
Best match: numpy 1.14.5
Adding numpy 1.14.5 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for pbcore==1.2.10
Best match: pbcore 1.2.10
Processing pbcore-1.2.10-py2.7.egg
pbcore 1.2.10 is already the active version in easy-install.pth
Installing dataset.py script to /home/aechchik/.local/bin
Installing .open script to /home/aechchik/.local/bin

Using /Home/aechchik/.local/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /software/lib/python2.7/site-packages
Searching for pysam==0.14
Best match: pysam 0.14
Adding pysam 0.14 to easy-install.pth file

Using /software/lib64/python2.7/site-packages
Searching for Cython==0.27.3
Best match: Cython 0.27.3
Adding Cython 0.27.3 to easy-install.pth file
Installing cython script to /home/aechchik/.local/bin
Installing cygdb script to /home/aechchik/.local/bin
Installing cythonize script to /home/aechchik/.local/bin

Using /software/lib64/python2.7/site-packages
Finished processing dependencies for pbh5tools==0.8.0
```

**Comment by jkaralius** [comment]
Hi @aechchiki 

Your command looks fine at first pass, however the GitHub repo for `pbh5tools` is 4 yrs old and not supported by PacBio.  I  recommend installing SMRT Analysis 2.3.0 and using the most recent version of `bash5tools` within `$SMRT_ROOT`.

https://www.pacb.com/support/software-downloads/

Joey
