### ISSUE TITLE
No Python3 support, incompatible with latest pbcore

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/pbh5tools#37]
Hi,
since Debian is droping Python2 in the next stable release we try hard to get rid of all Python2 dependencies.  Thus I created a [patch using 2to3](https://salsa.debian.org/med-team/pbh5tools/blob/master/debian/patches/2to3.patch) which you are perfectly welcome to cherry pick from.
Since latest pbcore supports Python3 I switched the Debian package to the latest git commit.  Unfortunately some modules that are used by pbh5tools were dropped.  This leads to the following errors in the build time test:

    $ cram3 -v doc/examples.t
    doc/examples.t: failed
    --- doc/examples.t
    +++ doc/examples.t.err
    @@ -14,95 +14,64 @@
     take 50% of the reads 
     
       $ cmph5tools.py select --where "SubSample(.5)" $INCMP --outFile ss.cmp.h5
    +  Traceback (most recent call last):
    +    File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/build/scripts-3.7/cmph5tools.py", line 43, in <module>
    +      from pbh5tools.CmpH5Select import cmpH5Select
    +    File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/.pybuild/cpython3_3.7_pbh5tools/build/pbh5tools/CmpH5Select.py", line 41, in <module>
    +      from pbcore.io import CmpH5Reader
    +  ImportError: cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py)
    +  [1]
       $ test -f ss.cmp.h5
    +  [1]
     ...
    $ find tests -name "*.py" | xargs nosetests3 -v
    Failure: ImportError (cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py)) ... ERROR
    Failure: ModuleNotFoundError (No module named 'pbcore.io.rangeQueries') ... ERROR
    
    ======================================================================
    ERROR: Failure: ImportError (cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py))
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/tests/test_cmph5lib_CmpH5Merge.py", line 8, in <module>
        from pbcore.io import CmpH5Reader
    ImportError: cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py)
    
    ======================================================================
    ERROR: Failure: ModuleNotFoundError (No module named 'pbcore.io.rangeQueries')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/tests/test_cmph5lib_CmpH5Sort.py", line 9, in <module>
        import pbh5tools.CmpH5Sort as CS
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/pbh5tools/CmpH5Sort.py", line 44, in <module>
        import pbcore.io.rangeQueries as RQ
    ModuleNotFoundError: No module named 'pbcore.io.rangeQueries'
    
    ----------------------------------------------------------------------
    Ran 2 tests in 0.002s
    
    FAILED (errors=2)
    make[2]: *** [Makefile:20: test] Error 123
    make[2]: Leaving directory '/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg'
    E: pybuild pybuild:341: test: plugin custom failed with: exit code=2: PATH=/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/build/scripts-2.7:/usr/sbin:/usr/bin:/sbin:/bin:/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/build/scripts-3.7 /usr/bin/make test
    dh_auto_test: pybuild --test --test-nose -i python{version} -p 3.7 returned exit code 13
    make[1]: *** [debian/rules:27: override_dh_auto_test] Error 255
    make[1]: Leaving directory '/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg'
    make: *** [debian/rules:11: build] Error 2
    dpkg-buildpackage: error: debian/rules build gave error exit status 2
    [0mI: copying local configuration[0m
    [0;31mE: Failed autobuilding of package[0m
    [0mI: user script /var/cache/pbuilder/build/cow.800774/tmp/hooks/C99_failed_build starting[0m
    Installing convenience apps: mc less bash-completion 
    [0mI: user script /var/cache/pbuilder/build/cow.800774/tmp/hooks/C99_failed_build finished[0m
    [0mI: unmounting /var/cache/pbuilder/extra/release filesystem[0m
    [0mI: unmounting /dev/shm filesystem[0m
    [0mI: unmounting dev/pts filesystem[0m
    [0mI: unmounting dev/shm filesystem[0m
    [0mI: unmounting proc filesystem[0m
    [0mI: unmounting sys filesystem[0m
    me 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py)) ... ERROR
    Failure: ModuleNotFoundError (No module named 'pbcore.io.rangeQueries') ... ERROR
    
    ======================================================================
    ERROR: Failure: ImportError (cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py))
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/tests/test_cmph5lib_CmpH5Merge.py", line 8, in <module>
        from pbcore.io import CmpH5Reader
    ImportError: cannot import name 'CmpH5Reader' from 'pbcore.io' (/usr/lib/python3/dist-packages/pbcore/io/__init__.py)
    
    ======================================================================
    ERROR: Failure: ModuleNotFoundError (No module named 'pbcore.io.rangeQueries')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
        raise self.exc_val.with_traceback(self.tb)
      File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/usr/lib/python3.7/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/lib/python3.7/imp.py", line 171, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/tests/test_cmph5lib_CmpH5Sort.py", line 9, in <module>
        import pbh5tools.CmpH5Sort as CS
      File "/build/pbh5tools-0.8.0+git20181212.9fa8fc4+dfsg/pbh5tools/CmpH5Sort.py", line 44, in <module>
        import pbcore.io.rangeQueries as RQ
    ModuleNotFoundError: No module named 'pbcore.io.rangeQueries'
    
    ----------------------------------------------------------------------
    Ran 2 tests in 0.002s
    
    FAILED (errors=2)

It would be great if you could check the compatibility with latest pbcore.
Kind regards, Andreas.

**Comment by tillea** [comment]
Any idea how the code could be adapted to latest pbcore?

**Comment by tillea** [comment]
Hi again,
in pbcore I've found a [commit](https://github.com/PacificBiosciences/pbcore/commit/11edfa7e) stating **Remove HDF5 support completely **.  It would help if you could clarify the status of phh5tools to enable me to decide whether it is worth keeping the package in Debian or rather drop it from the repository.
Thanks a lot, Andreas.
